services:
  # FastAPI
  api:
    build: ./api
    container_name: practice2-api
    ports:
      - "8000:8000"
    volumes:
      - ./videos:/data # Això connecta les carpetes automàticament
    depends_on:
      - ffmpeg

  # FFMPEG
  ffmpeg:
    build: ./ffmpeg
    container_name: practice2-ffmpeg
    volumes:
      - ./videos:/data # Això connecta les carpetes automàticament
    ports:
    - "9000:9000"

  # GUI
  gui:
    build: ./gui
    container_name: practice2-gui
    environment:
      - API_BASE=http://api:8000
    ports:
      - "8501:8501"
    volumes:
      - ./videos:/data